//void Uart0SendByte(unsigned char theByte);
bool Uart0GotByte(void);
//void Uart0WaitForByte(void);
unsigned char Uart0GetByte(void);
//void Uart0FlushBuffer(void);
//int Uart0PutChar(char c, FILE *stream);
void InitUart0(void);
//void Uart1SendByte(unsigned char theByte);
//bool Uart1GotByte(void);
//void Uart1WaitForByte(void);
//unsigned char Uart1GetByte(void);
//void Uart1FlushBuffer(void);
//int Uart1PutChar(char c, FILE *stream);
//void InitUart1(void);
